### ISSUE TITLE
Is there any example?

### ISSUE THREAD

**Issue by ringo2k** [Bonnee/thingiverse#1]
Hi, 

i am currently planning to write a python script which gets the pictures of a thing from thingiverse. I like to get the images of the thing and download them. 

I found your class, seems nice. But i didn't get how to work with it? Do you have a example or documentation? 

Thanks! 
regards 
ringo

**Comment by hroncok** [comment]
First of all, this is very rough code, so you'll might need to hack it around a bit (feel free to send pull requests). An example is here: https://github.com/hroncok/thingiverse_reranking/blob/master/thingiverse_reranking/views.py#L32
